# Generated by Django 3.2.3 on 2021-06-05 00:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='পোস্ট টাইটেল')),
                ('image', models.ImageField(default='', upload_to='Post/', verbose_name='ছবি')),
                ('body1', models.TextField(verbose_name='কন্টেন্ট ১ম অংশ')),
                ('body2', models.TextField(verbose_name='কন্টেন্ট ২য় অংশ')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='লেখক')),
            ],
        ),
    ]
