# Generated by Django 3.2.3 on 2021-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upazila', models.CharField(max_length=100, verbose_name='উপজেলা/থানা')),
            ],
            options={
                'verbose_name_plural': 'Upazilla',
            },
        ),
        migrations.CreateModel(
            name='Zilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zilla', models.CharField(max_length=100, verbose_name='জেলা')),
            ],
            options={
                'verbose_name_plural': 'Zilla',
            },
        ),
    ]
