# Generated by Django 3.2.3 on 2021-06-05 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=6, verbose_name='রক্তের গ্রুপ')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='সদস্য নাম')),
                ('phone', models.CharField(max_length=14, verbose_name='মোবাইল নাম্বার')),
                ('institution', models.CharField(max_length=100, verbose_name='শিক্ষা-প্রতিষ্ঠান')),
                ('ref_name', models.CharField(max_length=100, verbose_name='রেফারেন্স')),
                ('image', models.ImageField(default='', upload_to='Applicant/', verbose_name='ছবি')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bloodbank.upazila', verbose_name='উপজেলা/থানা')),
                ('zilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bloodbank.zilla', verbose_name='জেলা')),
            ],
            options={
                'verbose_name_plural': 'Applicant',
            },
        ),
    ]
