# Generated by Django 3.2.3 on 2021-06-05 02:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0003_auto_20210605_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='পদবি')),
            ],
            options={
                'verbose_name_plural': 'Designation',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='রক্তদাতা নাম')),
                ('phone', models.CharField(max_length=14, verbose_name='মোবাইল নাম্বার')),
                ('institution', models.CharField(max_length=100, verbose_name='শিক্ষা-প্রতিষ্ঠান')),
                ('number_donation', models.IntegerField(default=0, verbose_name='মোট রক্তদান')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='রক্তদানের-তারিখ')),
                ('location', models.CharField(max_length=100, verbose_name='উপজেলা')),
                ('zilla', models.CharField(max_length=100, verbose_name='জেলা')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bloodbank.bloodgroup', verbose_name='রক্তের গ্রুপ')),
            ],
            options={
                'verbose_name_plural': 'Donor',
                'ordering': ['blood_group'],
            },
        ),
    ]
