# Generated by Django 3.2.3 on 2021-06-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0006_organizationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField(verbose_name='বিস্তারিত-১')),
                ('description2', models.TextField(verbose_name='বিস্তারিত-২')),
                ('description3', models.TextField(verbose_name='বিস্তারিত-৩')),
                ('chairman_img', models.ImageField(default='', upload_to='chairman/', verbose_name='ছবি')),
            ],
        ),
    ]
