# Generated by Django 3.2.3 on 2021-06-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0008_auto_20210605_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='মাস')),
            ],
            options={
                'verbose_name_plural': 'Month',
            },
        ),
    ]
