# Generated by Django 3.2.3 on 2021-06-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0009_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bloodbank.month', verbose_name='মাস'),
        ),
    ]
