# Generated by Django 3.2.3 on 2021-06-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0012_auto_20210607_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='location',
            field=models.CharField(max_length=100, verbose_name='উপজেলা'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zilla',
            field=models.CharField(max_length=100, verbose_name='জেলা'),
        ),
    ]
